modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/minetraps/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minetraps:pitfall_trap"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/MineTraps_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minetraps"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This mod adds several new traps and blocks like mines, bear traps, nail traps, toxic mines, spikes and more!'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

